import markovify

import discord
from discord.ext import commands

class BCC(commands.Cog):
	def __init__(self, bot):
		self.bot = bot

	@commands.command()
	async def bcc(self, ctx):
		"""Short sentence generated by markovify chain"""
		with open('skills/bricolage_corpus.txt', 'r') as f:
			corpus = f.read()

		self.model = markovify.NewlineText(corpus, state_size=2)
		self.model.compile(inplace = True)

		response = self.model.make_short_sentence(120)
		await ctx.send(response)